# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_Ck_strict <- function(expr, spots, ligand, receptor) {
    .Call('_TWCOM_get_Ck_strict', PACKAGE = 'TWCOM', expr, spots, ligand, receptor)
}

get_Ck <- function(expr, spots, ligand, receptor) {
    .Call('_TWCOM_get_Ck', PACKAGE = 'TWCOM', expr, spots, ligand, receptor)
}

get_Ck_v <- function(expr, spots) {
    .Call('_TWCOM_get_Ck_v', PACKAGE = 'TWCOM', expr, spots)
}

get_Ms <- function(M, spots) {
    .Call('_TWCOM_get_Ms', PACKAGE = 'TWCOM', M, spots)
}

get_dist <- function(x, y, spots) {
    .Call('_TWCOM_get_dist', PACKAGE = 'TWCOM', x, y, spots)
}

if_neighbors <- function(X, Y, sample, dist) {
    .Call('_TWCOM_if_neighbors', PACKAGE = 'TWCOM', X, Y, sample, dist)
}

if_neighbors_samesample <- function(X, Y, dist) {
    .Call('_TWCOM_if_neighbors_samesample', PACKAGE = 'TWCOM', X, Y, dist)
}

